### ISSUE TITLE
Add request logging middleware

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/demo-nodejs#2]
Hey,

it'd be nice to have all request being logged. This  would demonstrate load balancing in action and also make it more easy to see that there's stuff going on.

Wdyt?

Thx!

**Comment by pragmaticivan** [comment]
I think it's a must-have feature in this boilerplate.

**Comment by zenorocha** [comment]
@pragmaticivan can you send a PR?

**Comment by cirocosta** [comment]
#3
